# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 578f2aee9720505d7ad96d8d7b609440656961495c4e8ef96e7bc303f0fc6c0139b9b531a1c8bd708e6b45586432cd0c419ff30d3509410b2ebc185b754a59d3

test:
  secret_key_base: 79791c64512a4ecb913d8b0df55849ade547b24d3526acff74255ea6ef8a8da8bfc40e917b73211d6fca1e9dc112cc7bf8777cc8011678841ded836f952ae3ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # temporary secret for production testing (faye and thin servers)
  secret_key_base: 1f970ae99698824c0d283eb0d21d3fda22fa71adf7cb0831b4228d490146d3772b727244fac1be07f8023444bab3768a1b4fb314f5a9237945a49a3f5dabf466
